### PR TITLE
Fix specialized std::vector<bool> handling

### PR DESCRIPTION
**Pull request by alexey-pelykh**

### CODE REVIEW

**Comment by SemaiCZE** [comment]
Hi,

as you can see this breaks all GCC builds. I know that `vector<bool>` is tricky because of multiple different platform specific implementations, but I won't merge it this way. I'd rather have a failing just MacOS than Mac and Linux on the most popular compiler.

Thanks

**Comment by alexey-pelykh** [comment]
I'll look closer, I don't anticipate it to be impossible at all.

**Comment by alexey-pelykh** [comment]
That's one way to tackle the issue, checked on latest GCC and Clang

**Comment by alexey-pelykh** [comment]
Cool, so it passes the tests. Obviously `g++-9: command not found` isn't related

**Comment by SemaiCZE** [comment]
Thanks for the PR :+1:.  I updated ubuntu and mac versions in the CI

**Pull request merged**
